### ISSUE TITLE
AWS client not being disposed of after use - SES Integration

### ISSUE THREAD

**Issue by tpflueger** [S2Cognition/S2Cognition.Integrations#18]
While using SES client integration, I noticed the client was being initialized without any cleanup but the client implements IDisposable interface -
https://github.com/S2Cognition/S2Cognition.Integrations/blob/75faf07846d98703436f8b862194f2e7aedf155e/S2Cognition.Integrations.AmazonWebServices.Ses/Models/AwsSesClient.cs#L22

**Comment by ericjpeters** [comment]
Got it.
